/**
 * Button — Polymorphic, variant-driven button atom.
 *
 * Renders as <button> by default but can be swapped to any element/component
 * via the `as` prop (e.g. `as="a"` for links, `as={Link}` for React Router).
 *
 * Design tokens consumed (all via CSS custom properties, light/dark-aware):
 *   Surfaces → bg-primary | bg-surface | bg-muted | bg-destructive
 *   Text     → text-on-primary | text-foreground | text-on-destructive
 *   Border   → border-border / ring-ring (focus)
 *
 * @example
 * // Text button
 * <Button variant="primary" size="md">Save changes</Button>
 *
 * // With leading icon
 * <Button variant="secondary" leftIcon={<PlusIcon />}>Add item</Button>
 *
 * // Icon-only (square, always include aria-label)
 * <Button variant="icon-only" aria-label="Delete"><TrashIcon /></Button>
 *
 * // Polymorphic — renders as <a>
 * <Button as="a" href="/dashboard" variant="ghost">Dashboard</Button>
 *
 * Install peer deps (if not already present):
 *   npm install class-variance-authority clsx tailwind-merge
 */

import React, {
  forwardRef,
  type ElementType,
  type ComponentPropsWithoutRef,
  type ReactNode,
} from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../../lib/utils';

// ─── Variant map ──────────────────────────────────────────────────────────────
// All color values reference CSS vars generated by build-tokens.js so they
// automatically switch between light and dark themes.

export const buttonVariants = cva(
  // ── Base styles applied to every button ──────────────────────────────────
  [
    // Layout
    'inline-flex items-center justify-center whitespace-nowrap',
    // Typography — text-small = 14px/20px, font-medium = 500 (from our token scale)
    'text-small font-medium',
    // Spacing between icon and label
    'gap-md',
    // Shape — rounded = 6px (our DEFAULT border radius token)
    'rounded',
    // Interaction
    'cursor-pointer select-none',
    'transition-colors duration-150 ease-in-out',
    // Focus ring — uses ring token (brand border color)
    'focus-visible:outline-none',
    'focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
    // Disabled
    'disabled:cursor-not-allowed disabled:opacity-50 disabled:pointer-events-none',
  ],
  {
    variants: {
      // ── Visual variant ────────────────────────────────────────────────────
      variant: {
        /**
         * Primary — brand-blue fill, white text. Main CTA.
         * Tokens: --color-primary[-hover|-active], --color-on-primary
         */
        primary: [
          'bg-primary text-on-primary',
          'hover:bg-primary-hover',
          'active:bg-primary-active',
        ],

        /**
         * Secondary — subtle surface with a border. Supporting action.
         * Tokens: --color-surface[-muted], --color-foreground, --color-border
         */
        secondary: [
          'bg-surface text-foreground',
          'border border-border',
          'hover:bg-muted',
          'active:bg-muted',
        ],

        /**
         * Destructive — red-filled. Danger / irreversible actions.
         * Tokens: --color-destructive[-hover|-active], --color-on-destructive
         */
        destructive: [
          'bg-destructive text-on-destructive',
          'hover:bg-destructive-hover',
          'active:bg-destructive-active',
        ],

        /**
         * Ghost — no background at rest; shows surface on hover. Minimal chrome.
         * Tokens: --color-surface[-muted], --color-foreground
         */
        ghost: [
          'bg-transparent text-foreground',
          'hover:bg-surface',
          'active:bg-muted',
        ],

        /**
         * Icon-only — square, centered icon, no visible label.
         * Uses primary brand colors. Always provide `aria-label`.
         * Compound variants below remove horizontal padding and set equal w/h.
         */
        'icon-only': [
          'bg-primary text-on-primary',
          'hover:bg-primary-hover',
          'active:bg-primary-active',
        ],
      },

      // ── Size ──────────────────────────────────────────────────────────────
      // Heights match Figma spec: sm=36px, md=40px, lg=44px
      // Padding uses our named spacing tokens: lg=12px, xl=16px, 4xl=32px
      size: {
        sm: 'h-9 px-lg',
        md: 'h-10 px-xl',
        lg: 'h-11 px-4xl',
      },
    },

    // ── Compound variants — icon-only overrides ───────────────────────────
    // Makes the button perfectly square and removes horizontal padding.
    compoundVariants: [
      { variant: 'icon-only', size: 'sm', className: 'w-9 p-0' },
      { variant: 'icon-only', size: 'md', className: 'w-10 p-0' },
      { variant: 'icon-only', size: 'lg', className: 'w-11 p-0' },
    ],

    defaultVariants: {
      variant: 'primary',
      size: 'md',
    },
  }
);

// ─── Polymorphic type helpers ─────────────────────────────────────────────────

type AsProp<C extends ElementType> = { as?: C };

type PropsToOmit<C extends ElementType, P> = keyof (AsProp<C> & P);

type PolymorphicComponentProp<C extends ElementType, Props = Record<string, never>> =
  React.PropsWithChildren<Props & AsProp<C>> &
  Omit<ComponentPropsWithoutRef<C>, PropsToOmit<C, Props>>;

// ─── Button-specific props ────────────────────────────────────────────────────

type ButtonBaseProps = VariantProps<typeof buttonVariants> & {
  /** Icon placed before the label */
  leftIcon?: ReactNode;
  /** Icon placed after the label */
  rightIcon?: ReactNode;
  /**
   * Shows a spinner and disables interaction.
   * The label remains visible for layout stability.
   */
  isLoading?: boolean;
  className?: string;
};

export type ButtonProps<C extends ElementType = 'button'> = PolymorphicComponentProp<
  C,
  ButtonBaseProps
>;

// ─── Spinner ──────────────────────────────────────────────────────────────────

function Spinner() {
  return (
    <svg
      className="animate-spin h-4 w-4 shrink-0"
      viewBox="0 0 24 24"
      fill="none"
      aria-hidden="true"
      focusable="false"
    >
      <circle
        className="opacity-25"
        cx="12"
        cy="12"
        r="10"
        stroke="currentColor"
        strokeWidth="4"
      />
      <path
        className="opacity-75"
        fill="currentColor"
        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
      />
    </svg>
  );
}

// ─── Icon slot wrapper ────────────────────────────────────────────────────────

function IconSlot({ children }: { children: ReactNode }) {
  return (
    <span className="inline-flex shrink-0 h-4 w-4" aria-hidden="true">
      {children}
    </span>
  );
}

// ─── Component ───────────────────────────────────────────────────────────────

// Inner render function — generic so it can infer the `as` type.
function ButtonInner<C extends ElementType = 'button'>(
  {
    as,
    variant = 'primary',
    size = 'md',
    leftIcon,
    rightIcon,
    isLoading = false,
    disabled,
    className,
    children,
    ...rest
  }: ButtonProps<C>,
  ref: React.Ref<Element>
) {
  const Component = (as ?? 'button') as ElementType;
  const isDisabled = disabled || isLoading;
  const isIconOnly = variant === 'icon-only';

  // <button> uses the `disabled` attribute; other elements use aria-disabled
  const disabledProps =
    Component === 'button'
      ? { disabled: isDisabled }
      : { 'aria-disabled': isDisabled || undefined };

  return (
    <Component
      ref={ref}
      data-loading={isLoading || undefined}
      data-variant={variant}
      data-size={size}
      className={cn(buttonVariants({ variant, size }), className)}
      {...disabledProps}
      {...rest}
    >
      {/* Loading spinner replaces the left icon slot */}
      {isLoading && <Spinner />}

      {/* Left icon (hidden when loading to avoid double-icon) */}
      {!isLoading && leftIcon && !isIconOnly && <IconSlot>{leftIcon}</IconSlot>}

      {/* Label — hidden in icon-only mode */}
      {!isIconOnly && (
        <span data-button-label className={cn(isLoading && 'opacity-70')}>
          {children}
        </span>
      )}

      {/* Icon-only content — children IS the icon */}
      {isIconOnly && (
        <span className="inline-flex shrink-0" aria-hidden="true">
          {children}
        </span>
      )}

      {/* Right icon (not shown in icon-only or when loading) */}
      {!isLoading && rightIcon && !isIconOnly && <IconSlot>{rightIcon}</IconSlot>}
    </Component>
  );
}

/**
 * Polymorphic Button atom.
 *
 * forwardRef is cast to preserve the generic type parameter —
 * this is the standard pattern for polymorphic + forwardRef in TypeScript.
 */
export const Button = forwardRef(ButtonInner) as <C extends ElementType = 'button'>(
  props: ButtonProps<C> & { ref?: React.Ref<Element> }
) => React.ReactElement | null;

// displayName for React DevTools
(Button as { displayName?: string }).displayName = 'Button';
